# Generated by Django 4.1.1 on 2022-10-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank name')),
                ('term_min', models.PositiveIntegerField(default=1, verbose_name='Minimum term')),
                ('term_max', models.PositiveIntegerField(default=30, verbose_name='Maximum term')),
                ('rate_min', models.PositiveIntegerField(default=1, verbose_name='Minimum rate')),
                ('rate_max', models.PositiveIntegerField(default=1, verbose_name='Minimum rate')),
                ('payment_min', models.PositiveIntegerField(default=0, verbose_name='Minimum payment')),
                ('payment_max', models.PositiveIntegerField(verbose_name='Maximum payment')),
            ],
            options={
                'verbose_name': 'bank_offer',
                'verbose_name_plural': 'bank offers',
                'db_table': 'bank_offers',
            },
        ),
    ]
