# Generated by Django 4.1.1 on 2022-10-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankoffer',
            name='rate_max',
            field=models.PositiveIntegerField(default=1, verbose_name='Maximum rate'),
        ),
    ]
