# Generated by Django 4.1.1 on 2022-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0002_alter_bankoffer_rate_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankoffer',
            name='monthly_payment',
            field=models.PositiveIntegerField(default=0, verbose_name='Monthly payment'),
        ),
    ]
