# Generated by Django 4.1.1 on 2022-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0003_bankoffer_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankoffer',
            name='rate_max',
            field=models.FloatField(default=1, verbose_name='Maximum rate'),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='rate_min',
            field=models.FloatField(default=1, verbose_name='Minimum rate'),
        ),
    ]
